# PrivateSubnetName = "terraform-azure-demo-vnet-private-subnet"
# PublicSubnetName = "terraform-azure-demo-vnet-public-subnet"
# PublicSecurityRuleSourceIpPrefix = "1.1.1.1/32"
# ResourceGroupName = "azure-ixnetwork-2-agents"
# SubscriptionId = "00000000-0000-0000-0000-000000000000"
# UserEmailTag = "terraform@example.com"
# UserLoginTag = "terraform"
# VnetName = "terraform-azure-demo-vnet-vnet"