# AppSshKeyName = "example-ssh-key-name"
# AwsAccessCredentialsAccessKey = " "
# AwsAccessCredentialsSecretKey = " "
# InboundIPv4CidrBlock = "1.1.1.1/32"
# UserEmailTag = "terraform@example.com"
# UserLoginTag = "terraform"
